server_url: ${HS_SERVER_URL:-http://localhost:8080}
listen_addr: 0.0.0.0:${HS_PORT:-8080}
metrics_listen_addr: 0.0.0.0:${HS_METRICS_PORT:-9090}
grpc_listen_addr: 0.0.0.0:50443
grpc_allow_insecure: false

private_key_path: /var/lib/headscale/private.key
db_type: sqlite3
db_path: /var/lib/headscale/db.sqlite
base_domain: ${HS_BASE_DOMAIN:-headscale.internal}

dns_config:
  nameservers:
    - ${HS_DNS1:-1.1.1.1}
    - ${HS_DNS2:-1.0.0.1}

acl_policy_path: /etc/headscale/acl_policy.hujson
log_level: ${HS_LOG_LEVEL:-info}
log_format: text

ip_prefixes:
  - fd7a:115c:a1e0::/48
  - 100.64.0.0/10

default_preauth_key_expiry: 24h
randomize_client_port: false
